### Recuperar información del inventario
GET http://localhost:1234/products

### Recuperar un producto por id
GET http://localhost:1234/products/Libros/EDQ201501ACAL8854343

### Recuperar todos los libros por género
GET http://localhost:1234/products/Libros?genre=enciclopedia+de+ciencias