### Recuperar información del inventario
GET http://localhost:1234/products

### Recuperar un producto por id
GET http://localhost:1234/products/EDQA201501CAL8854343

### Recuperar todos los libros por género
GET http://localhost:1234/products?genre=Arte

### Crear otro libro
POST http://localhost:1234/products
Content-Type: application/json

{
  "id": "",
  "name": "Trainspotting",
  "barcodes": [948346563],
  "type": "book",
  "providor": "Alex",
  "editorial": "Norton",
  "year": 1996,
  "authors": ["Irvine Welsh"],
  "genre": ["Novela", "Psiconautica"],
  "subgenre": ["Drogas", "Surrealismo"],
  "kind": "Line",
  "price": 380
}


###Editar un libro
PATCH http://localhost:1234/products/EDQA201501CEO2556808
Content-Type: application/json

{
  "year": 1970
}

### ELIMINA UN PRODUCTO
DELETE http://localhost:1234/products/EDQA201501CAL8854343